config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im-dashboard:
      branch: master
      repo: https://github.com/grycap/im-dashboard.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-cornflower-bloodhound.sh
        container: qc.acc_sloppy-pumpkin-quokka
  QC.Doc:
    repos:
      github.com/grycap/im-dashboard find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-gold-bonobo.sh
        container: qc.doc_greasy-silver-bison
      github.com/grycap/im-dashboard git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-flax-macaque.sh
        container: qc.doc_dorky-magenta-loon
      github.com/grycap/im-dashboard markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-goldenrod-owl.sh
        container: qc.doc_craggy-apricot-badger
  QC.Lic:
    repos:
      github.com/grycap/im-dashboard licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-amaranth-ostrich.sh
        container: qc.lic_homely-celadon-bracke
  QC.Met:
    repos:
      github.com/grycap/im-dashboard validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.ready-razzmatazz-earwig.sh
        container: qc.met_tasty-viridian-rabbit
  QC.Sec:
    repos:
      github.com/grycap/im-dashboard bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-plum-hedgehog.sh
        container: qc.sec_freaky-maroon-cow
  QC.Sty:
    repos:
      github.com/grycap/im-dashboard flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-cobalt-setter.sh
        container: qc.sty_trippy-cobalt-okapi
      github.com/grycap/im-dashboard hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-red-spider.sh
        container: qc.sty_surly-puce-vulture
      github.com/grycap/im-dashboard jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-ecru-heron.sh
        container: qc.sty_sleepy-pink-devil
  QC.Uni:
    repos:
      github.com/grycap/im-dashboard pytest:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-magenta-cassowary.sh
        container: qc.uni_crabby-teal-tarantula
  QC.Ver:
    repos:
      github.com/grycap/im-dashboard get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-cobalt-baboon.sh
        container: qc.ver_ugly-turquoise-discus
timeout: 5400
